### ISSUE TITLE
Not able to build for Mac Catalyst 

### ISSUE THREAD

**Issue by dal-mas** [couchbase/couchbase-lite-swift-ee#8]
Apparently, the .xcframework is missing on the binary. The community version works as expected.

**Comment by jayahariv** [comment]
what version did you use?

**Comment by dal-mas** [comment]
The latest stable version, 2.8.4

**Comment by jayahariv** [comment]
Could you please share the error details if you are getting any. 

I will try later today to download and use 2.8.4 SPM and see. Last time i checked it was working fine.

**Comment by erickmanaroulas** [comment]
When importing the package, I can reproduce this error with 100% accuracy. 

I get the following error message: 
`There is no XCFramework found at '/Users/<user>/Library/Developer/Xcode/DerivedData/<project>-banvzfxmqldepchikzinidpefvki/SourcePackages/artifacts/CouchbaseLiteSwift/CouchbaseLiteSwift.xcframework'.`

I found that, by changing build target to iPad and reseting caches, the error goes away when building for Mac Catalyst.

**Comment by jayahariv** [comment]
thanks @dal-mas and @erickmanaroulas 

Yea, I can successfully reproduce the issue. Please find the Jira tracking issue [CBL-2827](https://issues.couchbase.com/browse/CBL-2827).

**Comment by jayahariv** [comment]
Could you try delete the derived-data, reset the caches and resolve package.

**Comment by dal-mas** [comment]
@jayahariv, you're correct. Probably Xcode is getting confused with two CBL versions, closing the issue. Thanks!
